### ISSUE TITLE
Implement a 1-minute timer

### ISSUE THREAD

**Issue by exoduswalker** [ShamblesSM/OpenSMCE#1]
Title. This puts the Blitz in Zuma Blitz

**Comment by jakubg1** [comment]
Partially implemented in https://github.com/ShamblesSM/OpenSMCE/commit/3899e8f01188af435096ada2737c71ea49f555ec

To do:
- ~~Rewrite the structure a bit so the changes aren't permanent to a level and also the data can be used in UI scripts~~ done
- ~~Make it more graceful (so that existing chain combos can still be finished after the time runs out)~~ done
- ~~Remove the scarabs which give gems from the game altogether (this is a task to do in the main branch)~~ done
